package miinat.ui;

import java.awt.Color;
import miinat.engine.*;
import java.awt.GridLayout;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author Teemu Patja <tp@iki.fi>
 */
public class GUI 
extends 
        JFrame 
implements
        MouseListener,
        miinat.engine.IEngineObserver {

    
    private class UiSquare {
        
        private JLabel label;
        private Square square;
    
        UiSquare(Square s, JLabel l) {
            this.square = s;
            this.label = l;
        }
        
        public JLabel getLabel() {
            return this.label;
        }
        public void setLabel(JLabel l) {
            this.label = l;
        }
        public Square getSquare() {
            return this.square;
        }
        public void setSquare(Square s) {
            this.square = s;
        }
        
    }
    
    MiinaEngine engine;
    UiSquare[][] squares;
    GameState gameState;
    
    public enum GameState {
        Initial,
        GameRunning,
        GameWon,
        GameLost
    }
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        engine = new MiinaEngine(10,10,15, this);
        
        GridLayout gridLayout = new GridLayout(engine.getWidth(),engine.getHeight());
        setLayout(gridLayout);
        
        this.squares = new UiSquare[engine.getWidth()][engine.getHeight()];
        
        setSize(engine.getWidth()*20 + 10, engine.getHeight()*20 + 10);
        
        for(int y=0; y<engine.getHeight(); ++y) {
            for(int x=0; x<engine.getWidth(); ++x) {
                JLabel label = new JLabel();
                label.setOpaque(true);
                label.setSize(20,20);
                label.setBackground(Color.GRAY);
                label.setBorder( BorderFactory.createLineBorder(Color.BLACK) );
                label.addMouseListener(this);
                this.squares[x][y] = new UiSquare(engine.squareAt(x, y), label);
                add(label);
            }
        }
        
        gridLayout.addLayoutComponent(null, this);
        this.gameState = GameState.Initial;
        this.engine.init();
    }

    private void updateUi() {
        for(int y=0; y<engine.getHeight(); ++y) {
            for(int x=0; x<engine.getWidth(); ++x) {
                UiSquare s = this.squares[x][y];
                if(s.square.isCovered()) {
                    s.label.setBackground(Color.GRAY);
                    s.label.setText("");
                }
                else {
                    if(s.square.hasMine) {
                        s.label.setBackground(Color.RED);
                    }
                    else {
                        if (s.square.surroundingMines > 0)
                            s.label.setText(Integer.toString(s.square.surroundingMines));
                        s.label.setBackground(Color.WHITE);
                    }
                }
            }
        }
        this.repaint();
    }
    
    public void gameStarted() {
        System.out.println("gameStarted");
        this.gameState = GameState.GameRunning;
        for(int y=0; y<engine.getHeight(); ++y) {
            for(int x=0; x<engine.getWidth(); ++x) {
                this.squares[x][y].square = engine.squareAt(x, y);
            }
        }
        updateUi();
    }
    
    public void gameOver(boolean won) {
        System.out.println("gameOver, won:" + won);
        this.gameState = won ? GameState.GameWon : GameState.GameLost;
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Game");

        jMenuItem2.setText("New Game");
        jMenuItem2.setName(""); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, 
                "Miinat\n\nMinesweeper clone\nAuthor: Teemu Patja <tp@iki.fi>");
                
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed
        engine.init();
    }//GEN-LAST:event_newGameActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_exitActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    public void mouseClicked(MouseEvent e) {
        if(this.gameState != GameState.GameRunning) 
            return;
        
        Square sq = this.uiSquareByMouseEventSource( e.getSource() ).square;
        engine.uncoverSquare(sq.x, sq.y);
        this.updateUi();
    }
    
    private UiSquare uiSquareByMouseEventSource(Object o) {
       for(int y=0; y<engine.getHeight(); ++y) {
            for(int x=0; x<engine.getWidth(); ++x) {
                UiSquare us = this.squares[x][y];
                if(us.getLabel() == o)
                    return us;
            }
        }
       return null;

    }
    
    public void mousePressed(MouseEvent e) {
        
        
    }
    public void mouseReleased(MouseEvent e) {
        
    }
    public void mouseEntered(MouseEvent e) {
        
        if(this.gameState != GameState.GameRunning) 
            return;
        
        UiSquare us = this.uiSquareByMouseEventSource(e.getSource());
        if(us.getSquare().isCovered()) {
            us.getLabel().setBackground(Color.LIGHT_GRAY);
        }
    }
    public void mouseExited(MouseEvent e) {
        
        if(this.gameState != GameState.GameRunning) 
            return;
        UiSquare us = this.uiSquareByMouseEventSource(e.getSource());
        if(us.getSquare().isCovered()) {
            us.getLabel().setBackground(Color.GRAY);
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables


}
